import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card/Card'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center">
        <Card />
      </main>
    </div>
  )
}

export default Home
